version: "2.3"

services:
  mysql:
    image: mysql:5.7.20
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: demo-api
    ports:
      - "3306:3306"
    healthcheck:
        test: ["CMD", "mysqladmin", "ping", "-hmysql", "-uroot", "-proot", "--silent"]
        interval: 5s
        timeout: 3s
        retries: 5
  web:
    build: .
    command: rails s -p 3000 -b '0.0.0.0'
    ports:
      - "3000:3000"
    restart: always
    environment:
      DB_HOST: mysql
      DB_USER: root
      DB_PASS: root
      RAILS_ENV: ${RAILS_ENV}
      SECRET_KEY_BASE: ${SECRET_KEY_BASE}
    depends_on:
      mysql:
        condition: service_healthy
