default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV['DB_USER']%>
  password: <%= ENV['DB_PASS']%>
  host: <%= ENV['DB_HOST']%>
  port: 3306

development:
  <<: *default
  database: demo-api_development

test:
  <<: *default
  database: demo-api_test

production:
  <<: *default
  database: <%= ENV['DB_NAME']%>
